% Configurar el compilador en MATLAB: mex -setup C++
mex optitrack_sfunction.cpp ...
    -I"..\OptiTrack_Example\NatNet_SDK_4.3\NatNetSDK\include" ...
    -L"..\OptiTrack_Example\NatNet_SDK_4.3\NatNetSDK\lib\x64" ...
    -lNatNetLib

mex optitrack_sfunction_polling.cpp ...
    -I"..\OptiTrack_Example\NatNet_SDK_4.3\NatNetSDK\include" ...
    -L"..\OptiTrack_Example\NatNet_SDK_4.3\NatNetSDK\lib\x64" ...
    -lNatNetLib